Playmode scenarios documentation
Unity-Technologies/com.unity.multiplayer.docs pull request #1322
Opened 2024-08-12 16:51 UTC by Vic-Cooper

**Select the type of change:**
- [ ] Small Changes - Typos, formatting, slight revisions
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**
Adds new documentation for the Playmode Scenarios window and related properties.

**Issue Number:**
[DOCF-5362](https://jira.unity3d.com/browse/DOCF-5362)

2024-08-13 10:09 UTC, jabbacakes requested changes
Some inconsistencies here that need addressing, as well as that large and very confusing table on the Play Mode scenario window reference page.

2024-08-13 10:09 UTC, jabbacakes commented on mppm/troubleshoot/play-mode-scenario-troubleshoot.md
> +To troubleshoot an Error that appears when you enter Play Mode, refer to the Error message that appears in the console window. You can also open the [play mode scenario status dropdown](LINK) for mor
```suggestion
To troubleshoot an error that appears when you enter Play Mode, refer to the error message that appears in the console window. You can also open the [Play Mode scenario status dropdown](play-mode-scenario-dropdown-reference.md) for more information.
```

2024-08-13 10:09 UTC, jabbacakes commented on mppm/troubleshoot/play-mode-scenario-troubleshoot.md
> +* [Unity Game Service (UGS) Game Server Hosting (Multiplay)](https://docs.unity.com/ugs/en-us/manual/game-server-hosting/manual/welcome-to-multiplay)
```suggestion
* [Unity Gaming Services (UGS) Multiplay Hosting](https://docs.unity.com/ugs/en-us/manual/game-server-hosting/manual/welcome-to-multiplay)
```

2024-08-13 11:10 UTC, Vic-Cooper commented on mppm/mppm-reference/mppm-reference-lp.md
> +- [Create a Play Mode Scenario](play-mode-scenario-create.md)
correct! I'll go through and manage it, Scenario should really only be capitalised when referring to the window name.

2024-08-13 11:11 UTC, Vic-Cooper commented on mppm/mppm-reference/play-mode-scenario-window-reference.md
> +||Build Profile||The [Buld Profile](https://docs.unity3d.com/6000.0/Documentation/Manual/build-profiles.html) that this instance uses. When you build on a Windows device, select the Windows platform.
oopth

2024-08-13 11:13 UTC, Vic-Cooper commented on mppm/mppm-reference/play-mode-scenario-window-reference.md
> +||Multiplayer Role||The [multiplayer role](docs.unity3d.com/Packages/com.unity.dedicated-server@1.3/manual/multiplayer-roles.html) that this remote instance uses. Unity uses this Multiplayer Role and
Same property, same description, applies to different instance.

2024-08-13 11:14 UTC, Vic-Cooper commented on mppm/mppm-reference/play-mode-scenario-window-reference.md
> +
it is in the order in which the properties are presented. I do like the idea of beaking up the tables though. 
The content is grouped though, but I've just used multiple columns.

2024-08-13 11:15 UTC, Vic-Cooper commented on mppm/play-mode-scenario/play-mode-scenario-about.md
> +To test one or more instances of a multiplayer project on a local machine or a remote server, use the Play Mode Scenarios window. This window replicates the circumstances of a project that multiple u
It's a landing page really, which means I need to add a ToC for it, thanks!

2024-08-13 11:16 UTC, Vic-Cooper commented on mppm/play-mode-scenario/play-mode-scenario-create.md
> +3. Select **Configure play mode scenarios…**.
yes, yes it is...

2024-08-13 11:58 UTC, jabbacakes commented on mppm/mppm-reference/play-mode-scenario-window-reference.md
> +
Ah, fair enough. The table formatting is hard to parse in the raw markdown. But yeah, anything to make it clear that the things that seem the same, uh, aren't 😅

2024-08-13 11:59 UTC, jabbacakes commented on mppm/play-mode-scenario/play-mode-scenario-create.md
> +3. Select **Configure play mode scenarios…**.
Oh 😢

2024-08-13 19:06 UTC, johann-r-unity approved these changes
I did not see anything shocking. Approved, thanks Vic! 
Side question ; do we have a staging website?  It's easier to read.

2024-08-20 14:28 UTC, Vic-Cooper commented on mppm/mppm-reference/mppm-reference-lp.md
> +- [Create a Play Mode Scenario](play-mode-scenario-create.md)
Fixed all instances of this apitalisation in the next commit.

2024-08-20 14:51 UTC, jabbacakes commented on mppm/mppm-reference/play-mode-scenario-window-reference.md
> +||Multiplayer Role||The [multiplayer role](docs.unity3d.com/Packages/com.unity.dedicated-server@1.3/manual/multiplayer-roles.html) that this local instance uses. Unity uses this Multiplayer Role and
@Vic-Cooper This one doesn't seem to be resolved

2024-08-20 14:52 UTC, jabbacakes commented on mppm/play-mode-scenario/play-mode-scenario-req.md
> +A Play Mode Scenario that contains a local or remote instance requires a Build Profile that matches the platform your project exists on. To learn how to assign a Build profile, refer to [Create a Pla
@Vic-Cooper Capitalisation question here still unresolved.

2024-08-20 15:22 UTC, Vic-Cooper commented on mppm/play-mode-scenario/play-mode-scenario-req.md
> +A Play Mode Scenario that contains a local or remote instance requires a Build Profile that matches the platform your project exists on. To learn how to assign a Build profile, refer to [Create a Pla
hmnh. I'm gonna capitalize it consistently- the style guide has nothing for me here.

2024-08-20 15:44 UTC, jabbacakes approved these changes
👍

2024-08-20 16:09 UTC, merged