Adjust messaging examples to match v1.0.0 API
Unity-Technologies/com.unity.multiplayer.docs pull request #387
Opened 2021-11-03 20:44 UTC by NoxCaos

**Select the type of change:**

- [x] Small Changes - Typos, formatting, slight revisions
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**
Adjust `CustomMessagingManager` examples to match v1.0.0 API as it is now part of the `NetworkManager`

2021-11-03 20:44 UTC, unity-cla-assistant commented
[![CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/pull/badge/not_signed)](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=387) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=387) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=387) it.</sub>

2022-02-24 15:06 UTC, s-omeilia-unity commented
@TwoTenPvP I'm cleaning up all the open Docs PRs. Is this content accurate for me to merge?

2022-02-24 15:26 UTC, TwoTenPvP requested changes
With these changes, the content is accurate and should be merged :)

2022-02-24 15:26 UTC, TwoTenPvP commented on versioned_docs/version-1.0.0/advanced-topics/message-system/custom-messages.md
> +    NetworkManager.CustomMessagingManager.RegisterNamedMessageHandler("myMessageName", (senderClientId, reader) =>
```suggestion
    NetworkManager.Singleton.CustomMessagingManager.RegisterNamedMessageHandler("myMessageName", (senderClientId, reader) =>
```

2022-02-24 15:26 UTC, TwoTenPvP commented on versioned_docs/version-1.0.0/advanced-topics/message-system/custom-messages.md
> +    NetworkManager.CustomMessagingManager.SendNamedMessage("myMessageName", clientId, writer, NetworkDelivery.Reliable); //NetworkDelivery is optional.
```suggestion
    NetworkManager.Singleton.CustomMessagingManager.SendNamedMessage("myMessageName", clientId, writer, NetworkDelivery.Reliable); //NetworkDelivery is optional.
```

2022-02-24 15:26 UTC, TwoTenPvP commented on versioned_docs/version-1.0.0/advanced-topics/message-system/custom-messages.md
> +    NetworkManager.CustomMessagingManager.SendUnnamedMessage(clientId, writer, NetworkDelivery.Reliable); //NetworkDelivery is optional.
```suggestion
    NetworkManager.Singleton.CustomMessagingManager.SendUnnamedMessage(clientId, writer, NetworkDelivery.Reliable); //NetworkDelivery is optional.
```

2022-02-24 15:26 UTC, TwoTenPvP commented on versioned_docs/version-1.0.0/advanced-topics/message-system/custom-messages.md
> +    NetworkManager.CustomMessagingManager.OnUnnamedMessage += ((senderClientId, reader) =>
```suggestion
    NetworkManager.Singleton.CustomMessagingManager.OnUnnamedMessage += ((senderClientId, reader) =>
```

2022-07-28 20:51 UTC, s-omeilia-unity commented
Closing this PR because all of the API refs are being rebuilt from scratch with the most up-to-date content for the 1.0.0 full release.

2022-07-28 20:51 UTC, closed without merging