audit: networktransform [MTT-3782]
Unity-Technologies/com.unity.multiplayer.docs pull request #656
Opened 2022-07-06 15:44 UTC by NoelStephensUnity

**Select the type of change:**

- [X] Small Changes - Typos, formatting, slight revisions
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**
Audit NetworkTransform documentation.

**Issue Number:** 
[MTT-3782](https://jira.unity3d.com/browse/MTT-3782)

2022-07-06 15:58 UTC, chrispope requested changes
removing an empty space

2022-07-06 15:58 UTC, chrispope commented on docs/components/networktransform.md
> +The threshold values can be used to set a minimum threshold value. Whether to properly scale to your project's world unit scale or to reduce the frequency of synchronization updates, changes below th
```suggestion
The threshold values can be used to set a minimum threshold value. Whether to properly scale to your project's world unit scale or to reduce the frequency of synchronization updates, changes below threshold values will not be synchronized. For example, if your NetworkTransform has Interpolate enabled you might find that you can lower your position threshold resolution (i.e. position threshold value increased) without impacting the "smoothness" of an object's motion. Increasing the threshold value (lowering the resolution of synchronization updates) will reduce the frequency of when the object's position is synchronized which translates to reducing bandwidth consumption.
```

2022-07-06 17:25 UTC, NoelStephensUnity commented on docs/components/networktransform.md
> +The threshold values can be used to set a minimum threshold value. Whether to properly scale to your project's world unit scale or to reduce the frequency of synchronization updates, changes below th
Nice catches!

2022-07-07 09:00 UTC, chrispope approved these changes

2022-07-11 17:36 UTC, s-omeilia-unity approved these changes

2022-07-11 17:36 UTC, merged