Updating the HelloWorld instructions Player Settings
Unity-Technologies/com.unity.multiplayer.docs pull request #811
Opened 2022-10-06 10:41 UTC by chrispope

Updating the HelloWorld instructions for Player Settings to make it clearer to follow.

**Select the type of change:**

- [X] Small Changes - Typos, formatting, slight revisions
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**
Updating the HelloWorld instructions for Player Settings to make it clearer to follow.

**Issue Number:** 
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/issues/780

2022-10-06 20:26 UTC, armstrongl requested changes

2022-10-06 20:26 UTC, armstrongl commented on docs/tutorials/helloworld.md
> +1. Back in the Editor, open **Edit** -> **Project Settings** and select the **Player tab**. click **Resolution and Presentation** to open the section options.
Very minor suggestion :)

> Back in the Editor, select **Edit** > **Project Settings**.
> Select the **Player** tab, then expand the **Resolution and Presentation** section.

2022-10-13 19:26 UTC, armstrongl requested changes

2022-10-13 19:26 UTC, armstrongl commented on docs/tutorials/helloworld.md
> +1. Back in the Editor, open **Edit** -> **Project Settings** and select the **Player tab**. then expand the **Resolution and Presentation** to open the section options.
Minor edit suggestion:

> 1. Back in the Editor, select **Edit** > **Project Settings**.
> 2. Select the **Player** tab, then expand the **Resolution and Presentation** to open the section options.

2022-10-18 09:03 UTC, MorwennaG commented on docs/tutorials/helloworld.md
> +1. Select the **Player tab**. then expand the **Resolution and Presentation** to open the section options.
I would probable make this - expand Resolution and Presentation _or_ expand the Resolution and Presentation tab.

2022-10-18 09:14 UTC, MorwennaG approved these changes

2022-10-18 09:17 UTC, merged