update namings, fix minor technical details, other polish & cleanup
Unity-Technologies/com.unity.multiplayer.docs pull request #86
Opened 2021-03-23 12:07 UTC by MFatihMAR

**Select the type of change:**

- [x] Small Changes - Typos, formatting, slight revisions
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**

- `IBitWritable` → `INetworkSerializable`
- `PooledBitWriter` → `PooledNetworkWriter`
- `PooledBitReader` → `PooledNetworkReader`
- `IsReliable` bool → `Delivery` enum
- `ServerRPC` → `ServerRpc`
- `ClientRPC` → `ClientRpc`
- `BitWriter` → `NetworkWriter`
- `BitReader` → `NetworkReader`
- `BitSerializer` → `NetworkSerializer`
- `AutoBitWritable` → `AutoNetworkSerializable`
- remove pseudo-code blocks from `NetworkUpdateLoop` page
  - implementation differs from the pseudo-code we proposed on the RFC side
- use Visual Studio light & dark themes instead of default built-in themes
- fix/update minor technical details in serialization doc

**Issue Number:**

2021-03-23 12:09 UTC, MFatihMAR commented on docs/advanced-topics/message-system/rpc-params.md
> +:::
actually, this tip block was the main purpose of this PR but I ended up cleaning bunch of other stuff as well :)

2021-03-23 12:32 UTC, Briancoughlin approved these changes
Made some minor updates to a few files to reflect the edits from Fatih and files that were missing from sidebar.

2021-03-23 14:13 UTC, lkrell requested changes
Remove the yarn.lock edits it will break the site. Everything uses npm.
Your IDE force changed spacing in our build files (package.json and docusaurus.config.js) that I need to verify/revert.
Reviewing all other content, just putting this change in so we don't push this to any build. It will break.

2021-03-23 14:18 UTC, MFatihMAR commented
@lkrell — I think we should update `.gitignore` so that it won't pick up `yarn.lock`.
The other changes in `package.json` and `docusaurus.config.js` files are safe though, I don't understand why we "have to" revert spacing changes.
also I wonder how can somebody check if the PR would break the build or not and also why that check is not the part of PR?

2021-03-23 14:41 UTC, lkrell commented
I am fixing these files to clear the PR

2021-03-23 14:42 UTC, lkrell commented
.gitignore does include the yarn.lock which is odd. No worries!

2021-03-23 14:44 UTC, lkrell commented
Docs: Testing build. Verifying content. When passed will approve and move pr into merging.

2021-03-23 14:45 UTC, merged

2021-08-05 08:53 UTC, PioneerRedwood commented
Hello, you Top developers.
Those image links are not working. Would you mind to fix it?

https://github.com/Unity-Technologies/com.unity.multiplayer.docs/blob/master/docs/advanced-topics/network-update-loop-system/network-update-loop-reference.md

2021-08-05 13:44 UTC, MFatihMAR commented
are they really broken? @PioneerRedwood 
they're perfectly fine here:
https://docs-multiplayer.unity3d.com/docs/develop/advanced-topics/network-update-loop-system/network-update-loop-reference

2021-08-05 13:48 UTC, PioneerRedwood commented
Oh, they broken just in readme.md file. It's OK, thank you @MFatihMAR !!